### ISSUE TITLE
Data/config.yml not found

### ISSUE THREAD

**Issue by wolverine30008** [stigger/trakt-for-appletv#10]
Hi Stigger,

When i run the python3 ./tvscrobbler.py comand on terminal I receive data/config.yml not found. I have located it myself so I don’t understand was the error is created.

Is this supported on Mac and Appletv 4K with the latest TVOS?

Any help or advice is appreciated. Thank you for your hard work and support.

**Comment by stigger** [comment]
> Is this supported on Mac and Appletv 4K with the latest TVOS?

Yes, it is.

> When i run the python3 ./tvscrobbler.py comand on terminal I receive data/config.yml not found

Can you show me the entire output from the terminal?

**Comment by wolverine30008** [comment]
python3 /Users/wolverine30008/Downloads/trakt-for-appletv-master/tvscrobbler.py  

Traceback (most recent call last):

  File "/Users/wolverine30008/Downloads/trakt-for-appletv-master/tvscrobbler.py", line 53, in <module>

    launch(ScrobblingRemoteProtocol(load_config()))

  File "/Users/wolverine30008/Downloads/trakt-for-appletv-master/tvscrobbler.py", line 21, in load_config

    config = yaml.load(open('data/config.yml', 'r'))

FileNotFoundError: [Errno 2] No such file or directory: 'data/config.yml'

    On Sunday, March 29, 2020, 4:27:42 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 



Is this supported on Mac and Appletv 4K with the latest TVOS?


Yes, it is.


When i run the python3 ./tvscrobbler.py comand on terminal I receive data/config.yml not found


Can you show me the entire output from the terminal?

**Comment by stigger** [comment]
`/Users/wolverine30008/Downloads/trakt-for-appletv-master` has to be your working directory when launching it.

**Comment by wolverine30008** [comment]
After typing in the trakt authorization code I am receiving another error stating transport sockets cannot be blocking

20235cc68899dbbfb4fbc171384c1c1d30d7d4&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code

Authorization code: 86CA5B46

Exception in callback ScrobblingRemoteProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)

handle: <Handle ScrobblingRemoteProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run

    self._context.run(self._callback, *self._args)

  File "/Users/wolverine30008/Downloads/trakt-for-appletv-master/scrobbling.py", line 52, in connection_made

    super().connection_made(transport)

  File "/Users/wolverine30008/Downloads/trakt-for-appletv-master/media_remote.py", line 42, in connection_made

    socket.setblocking(True)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/trsock.py", line 197, in setblocking

    raise ValueError(

ValueError: setblocking(): transport sockets cannot be blocking

    On Sunday, March 29, 2020, 5:02:39 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


/Users/wolverine30008/Downloads/trakt-for-appletv-master has to be your working directory when launching it.

**Comment by stigger** [comment]
Python 3.8 is not supported yet, please use Python 3.7.

**Comment by wolverine30008** [comment]
ok I got to the point where the apple tv displayed a code.  I entered it and the last read out is below.  Is it activated now, as it never asked for trakt authorization again, just the appletv code. Am I missing any steps?
 
Enter code displayed by Apple TV: 1669

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/x25519.py:35: CryptographyDeprecationWarning: public_bytes now requires encoding and format arguments. Support for calling without arguments will be removed in cryptography 2.7

  utils.DeprecatedIn25,

ready!



    On Sunday, March 29, 2020, 6:34:10 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


Python 3.8 is not supported yet, please use Python 3.7.

**Comment by wolverine30008** [comment]
ok I got to the point where the apple tv displayed a code.  I entered it and the last read out is below.  Is it activated now, as it never asked for trakt authorization again, just the appletv code. Am I missing any steps?

Enter code displayed by Apple TV: 1669

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/x25519.py:35: CryptographyDeprecationWarning: public_bytes now requires encoding and format arguments. Support for calling without arguments will be removed in cryptography 2.7

  utils.DeprecatedIn25,

ready!

**Comment by stigger** [comment]
No, it should just work now.

**Comment by wolverine30008** [comment]
Trakt is not scrobbling watched content when using the Apple TV app or using the tv shows app on the Apple TV. It is not working.  Is there a way I can remove the original trakt authorization and submit it again.  If you remember I did not know to cd into the folder before running the scripts and authorization was done outside of the root folder. Simply, how do I remove the original trakt authorization. Also it is not listed under my api or apps folder in Trakt so maybe the authorization never took.

**Comment by stigger** [comment]
Delete the file `trakt.auth` and run again.
