### ISSUE TITLE
Syntax error line 41

### ISSUE THREAD

**Issue by wolverine30008** [stigger/trakt-for-appletv#2]
Hi stigger,

Hope you can help.  I have been at this all day. I followed the readme but when running python on tvscrobbler on both pc and Mac I get starting with python3 and the path to the tvscrobbler.py

trakt-foappletvr--master\tvscrobbler.py, line 41 asyncio.async(loop.create_connection(lambda: tv_protocol, info.server, info.port))

SyntaxError: Invalid syntax

What am I doing wrong? Any help or advice is appreciated.

**Comment by stigger** [comment]
Hi, what's the exact python version that you are using?

**Comment by wolverine30008** [comment]
Hi,
Python 3.7.2


Sent from Yahoo Mail for iPad


On Sunday, March 10, 2019, 1:55 PM, Vyacheslav Karpukhin <notifications@github.com> wrote:


Hi, what's the exact python version that you are using?

**Comment by stigger** [comment]
Thanks, turns out there was a compatibility issue with Python 3.7. Should be fixed now, please re-download and try again.

**Comment by wolverine30008** [comment]
Hi,
I am receiving a strange error stating “ no such file or directory config.yml. Maybe test it out for yourself and you will find the same.  Also on pc I was getting zeroconfig browser error which if I rememeber correctly was a component of a Mac.  This leaves me to believe this is a Mac only program.  
I apppreciate the help and support.  I would love to get this working as its the missing link for me.

Thanks again

**Comment by wolverine30008** [comment]
I know what your thinking the file is clearly visible on the commits page but for some strange reason terminal is saying it is not.

**Comment by stigger** [comment]
> no such file or directory config.yml.

Please try to `cd` to the project directory before launching.

> Also on pc I was getting zeroconfig browser error which if I rememeber correctly was a component of a Mac. This leaves me to believe this is a Mac only program.

Haven't tested on Windows, but works perfectly well for me on Linux.

**Comment by wolverine30008** [comment]
Ok almost there now I have accessed trakt.tv from the navigate url from terminal in order to get an authorization code but I get the trakt logo with OAUTH ERROR.  I assume I had to copy and paste the entire url up to type=code 
Appreciate the prompt support. 


Sent from Yahoo Mail for iPad


On Sunday, March 10, 2019, 7:06 PM, Vyacheslav Karpukhin <notifications@github.com> wrote:



no such file or directory config.yml.


Please try to cd to the project directory before launching.


Also on pc I was getting zeroconfig browser error which if I rememeber correctly was a component of a Mac. This leaves me to believe this is a Mac only program.


Haven't tested on Windows, but works perfectly well for me on Linux.
