### ISSUE TITLE
OAUTH ERROR TRAKT

### ISSUE THREAD

**Issue by wolverine30008** [stigger/trakt-for-appletv#3]
Ok almost there now I have accessed trakt.tv from the navigate url from terminal in order to get an authorization code but I get the trakt logo with OAUTH ERROR.  I assume I had to copy and paste the entire url up to type=code 
Appreciate the prompt support.

**Comment by stigger** [comment]
Please try again, should be fixed.

**Comment by wolverine30008** [comment]
Ok I was able to get through with code and now terminal has ends with the utils.DeprecatedIn25, ready! Does this mean it worked?
Thanks again


Sent from Yahoo Mail for iPad


On Monday, March 11, 2019, 7:56 PM, Vyacheslav Karpukhin <notifications@github.com> wrote:


Please try again, should be fixed.

**Comment by stigger** [comment]
Yes, if the Apple TV showed you a code, you entered it and have seen "ready!", then everything should be OK.

**Comment by wolverine30008** [comment]
Thank-You so much.  I plan to show my support as well.
I will keep you posted.


Sent from Yahoo Mail for iPad


On Monday, March 11, 2019, 8:22 PM, Vyacheslav Karpukhin <notifications@github.com> wrote:


Yes, if the Apple TV showed you a code, you entered it and have seen "ready!", then everything should be OK.
