### ISSUE TITLE
Question: Is it possible to install on another OS?

### ISSUE THREAD

**Issue by iFredOS** [stigger/trakt-for-appletv#7]
I want to use it on a Synology NAS. Is it possible?

**Comment by stigger** [comment]
I don't know, but Synology can run Docker containers, so probably that should work.

**Comment by CelticWebSolutions** [comment]
Thanks for your work on this.  I’m very interested in it, I’ve been hunting for an Apple TV > Trakt integration for some time.  Do you know if there is already a docker container with your software on available? I’d like to run it exactly like the op of this request.

Thanks in advance for any help you can offer.

**Comment by stigger** [comment]
No, I don't think there are any already built Docker images. But building from the included Dockerfile should work.

**Comment by CelticWebSolutions** [comment]
Thanks for the prompt response, not built a docker image before but I'll give it a go.  if it works, I'll post it up for others to use :)

Thanks again!

**Comment by stigger** [comment]
Looks like it should work on pretty much any system that's capable of running docker containers.
